Issue 13 wildcard mask
Sija/ipaddress.cr pull request #14
Opened 2021-09-14 11:43 UTC by bwks

added `wildcard_mask` method

This PR aims to resolve #13

2021-09-14 11:45 UTC, bwks commented
I will also update the README

2021-09-14 11:57 UTC, Sija requested changes

2021-09-14 11:57 UTC, Sija commented on src/ipaddress/ipv4.cr
> +    def wildcard_mask : String
I'd move it into the `Prefix32` struct, `Prefix128` for instance doesn't support it.

2021-09-17 14:27 UTC, closed without merging

2021-09-17 14:39 UTC, Sija commented
@bwks I've merged #15, in which I moved the method into the `Prefix32` struct, so you can use it like:

```cr
ip = IPAddress.new "172.16.100.4/22"
if ip.is_a?(IPAddress::IPv4)
  ip.prefix.wildcard_mask # => "0.0.3.255"
end
```

See if that resolves your issue please and if yes, I'll release a new shard version.

2021-09-17 20:44 UTC, bwks commented
Hey @Sija thank you very much for this. I am sorry I didn't get back to you sooner. Work has been flat out in the last couple of days and was going to come back to this on the weekend. I noticed that there is already a `Prefix32#hostmask` method when I was reading through the code and I believe it does the same thing.

https://github.com/Sija/ipaddress.cr/blob/9b16a958963b566353c88b94c1674c2764e3f3d3/src/ipaddress/prefix.cr#L179
```crystal
    # The hostmask is the contrary of the subnet mask,
    # as it shows the bits that can change within the
    # hosts.
    #
    # ```
    # prefix = IPAddress::Prefix32.new 24
    # prefix.hostmask # => "0.0.0.255"
    # ```
    def hostmask : String
      octets.join('.') { |i| ~i.to_u8 }
    end
  end
```

Please correct me if im wrong, but maybe you already implemented it and forgot? This new method may be unnecessary.

2021-09-17 21:10 UTC, Sija commented
Haha, you're so right 😅

2021-09-17 21:16 UTC, bwks commented
🤣 
Thank so much anyway for the support ❤. I learned a lot just attempting this.